---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  patch-notes:
    title: Patch Notes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: contentpage
    hero-image: ''
- scope:
    path: ''
    type: patch-notes
  values:
    layout: patchnotes
    release-date: ''
- scope:
    path: ''
    type: news
  values:
    layout: contentpage
    subtitle: ''
    main-image: ''
    hero-image: ''
permalink: pretty
banner-image: "/uploads/FRI-01-Jason-RainV2.jpg"
banner-title-line-1: G-Strings
banner-title-line-2: and Dead Things
banner-subtitle: The 1984 Swim Season has hit Camp Crystal Lake in an all new DLC!
banner-link-title: Read More
banner-link-url: "/spring-break-1984-clothing-pack/"
featured-box-1-title: Virtual Cabin 2.0
featured-box-1-subtitle: What it is and why you should care.
featured-box-1-url: news/virtual-cabin-2-dot-0/
new-window-1: false
featured-box-1-image: "/uploads/VC_Featured2-770a83.jpg"
featured-box-2-title: Content Creator of the Week
featured-box-2-subtitle: Campfacer
featured-box-2-url: https://www.twitch.tv/campfacer
new-window-2: false
featured-box-2-image: "/uploads/omegleheader.png"
featured-box-3-title: Spring Break '84 Clothing Pack
featured-box-3-subtitle: Bikini's, trunks and gore!
featured-box-3-url: "/news/spring-break-1984-clothing-pack/"
new-window-3: false
featured-box-3-image: "/uploads/Spring-Break-Clothing_featured-1.png"
stream-1-title: He's pretty deadly as Jason, we're just saiyan...
stream-1-subtitle: VEGETTA777
stream-1-url: https://www.youtube.com/user/vegetta777/search?query=friday+the+13th
stream-1-image: "/uploads/VEGETTA777.jpg"
stream-2-title: Jason Rex
stream-2-subtitle: Willyrex
stream-2-url: https://www.youtube.com/user/Willyrex/search?query=friday+the+13th
stream-2-image: "/uploads/Willyrex.jpg"
stream-3-title: An Honest Game Trailer
stream-3-subtitle: Smosh Games
stream-3-url: https://www.youtube.com/watch?v=Xw7wr4oPQy4
stream-3-image: "/uploads/Honest%20Trailers.jpg"
stream-4-title: Where Do We Rank?
stream-4-subtitle: gameranx
stream-4-url: https://www.youtube.com/watch?v=YCT0uyl46G8
stream-4-image: "/uploads/GamerRanx.jpg"
stream-5-title: How Angry Can He Get?
stream-5-subtitle: AngryJoeShow
stream-5-url: https://www.youtube.com/watch?v=sq_n226d2k8
stream-5-image: "/uploads/AngryJoeShow.jpg"
stream-6-title: How Fun Is This Game?
stream-6-subtitle: Previously Recorded
stream-6-url: https://www.youtube.com/user/PreRecRLM/search?query=friday+the+13th
stream-6-image: "/uploads/Previously%20Recorded.jpg"
player-highlight-title: JenTheStrange
player-highlight-url: https://www.twitch.tv/jenthestrange
player-highlight-icon-image: "/uploads/player-icon.png"
player-highlight-image: "/uploads/asian%20charmz.png"
