---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  patch-notes:
    title: Patch Notes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: contentpage
    hero-image: ''
- scope:
    path: ''
    type: patch-notes
  values:
    layout: patchnotes
    release-date: ''
    hide-date-show-title: true
- scope:
    path: ''
    type: news
  values:
    layout: contentpage
    subtitle: ''
    main-image: ''
    hero-image: ''
permalink: pretty
banner-image: "/uploads/FRI-01-Jason-RainV2.jpg"
banner-title-line-1: Dying
banner-title-line-2: For News?
banner-subtitle: Scroll to see what we're working on, patch notes, future content
  and more.
banner-link-title: Read More
banner-link-url: "/read-more"
featured-box-1-title: Featured Content
featured-box-1-subtitle: Emote DLC Pack 1
featured-box-1-url: "/news/emote-dlc-1-2/ "
new-window-1: false
featured-box-1-image: "/uploads/new_emotes-featured.jpg"
featured-box-2-title: Content Creator of the Week
featured-box-2-subtitle: GhostWolfGames
featured-box-2-url: https://www.youtube.com/channel/UCWFcFizUKTh1kmBxuSQOshg
new-window-2: true
featured-box-2-image: "/uploads/featured2.jpg"
featured-box-3-title: Spring Break '84 Clothing Pack
featured-box-3-subtitle: Righteous threads
featured-box-3-url: "/news/spring-break-1984-clothing-pack/"
new-window-3: false
featured-box-3-image: "/uploads/springbreak-featured.jpg"
stream-1-title: The Maskedgamer in the flesh!
stream-1-subtitle: Ohmwrecker
stream-1-url: https://www.youtube.com/playlist?list=PLWWOl-2iqjMZF53i0K6A0hkmsBS8WhGQR
stream-1-image: "/uploads/Ohmwrecker.jpg"
stream-2-title: Can an elephant hold a machete?
stream-2-subtitle: Gorillaphent
stream-2-url: https://www.youtube.com/channel/UCW8OeVwJvsGMv28FVnK0X5Q/videos?shelf_id=1&view=0&sort=p
stream-2-image: "/uploads/gorillaphent.jpg"
stream-3-title: Axes, teddy bears and laughter.
stream-3-subtitle: H20 Delirious
stream-3-url: https://www.youtube.com/playlist?list=PLq5wWza3lMAYoxjwhcsDM7nS3I2jZVrom
stream-3-image: "/uploads/H20.jpg"
stream-4-title: Total shenanigans, all the time!
stream-4-subtitle: BryceGames
stream-4-url: https://www.youtube.com/playlist?list=PLhuoUg_YfeT-51TywlTAoyB88WZu62K5z
stream-4-image: "/uploads/Bryce.jpg"
stream-5-title: Card carrying F13 Army member!
stream-5-subtitle: Laphin
stream-5-url: https://www.twitch.tv/laphin
stream-5-image: "/uploads/Laphin.jpg"
stream-6-title: An all-around KILLER streamer.
stream-6-subtitle: Swiftor
stream-6-url: https://www.youtube.com/playlist?list=PL5r-ii6ChwOi83FR4oFRqlq0FhT7u7gGn
stream-6-image: "/uploads/Swiftor2.jpg"
player-highlight-title: whiteboyspud5
player-highlight-url: https://my.playstation.com/whiteboyspud5
player-highlight-icon-image: "/uploads/player-icon.png"
player-highlight-image: "/uploads/POTW1.jpg"
