---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  patch-notes:
    title: Patch Notes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: contentpage
    hero-image: ''
- scope:
    path: ''
    type: patch-notes
  values:
    layout: patchnotes
    release-date: ''
- scope:
    path: ''
    type: news
  values:
    layout: contentpage
    subtitle: ''
    main-image: ''
    hero-image: ''
permalink: pretty
banner-image: "/uploads/FRI-01-Jason-RainV2.jpg"
banner-title-line-1: A New
banner-title-line-2: 'Beginning. '
banner-subtitle: We revamped the website for our incredible community of fans!
banner-link-title: Read More
banner-link-url: "/read-more"
featured-box-1-title: Free Emote DLC
featured-box-1-subtitle: Wave at Jason...Just before he kills you.
featured-box-1-url: "/news/emote-dlc-1-2/ "
new-window-1: false
featured-box-1-image: "/uploads/new_emotes-featured.jpg"
featured-box-2-title: Content Creator of the Week
featured-box-2-subtitle: Laphin Hyena
featured-box-2-url: https://www.twitch.tv/laphin
new-window-2: true
featured-box-2-image: "/uploads/laphin-bb85d9.jpg"
featured-box-3-title: Spring Break '84 Clothing Pack
featured-box-3-subtitle: Bikini's, trunks and gore!
featured-box-3-url: "/news/spring-break-1984-clothing-pack/"
new-window-3: false
featured-box-3-image: "/uploads/springbreak-featured.jpg"
stream-1-title: We made him jump!
stream-1-subtitle: DashieGames
stream-1-url: https://www.youtube.com/watch?v=cRPljNO7x2A&ab_channel=DashieGames
stream-1-image: "/uploads/DashieGames.jpg"
stream-2-title: How does this clan fare against Jason?
stream-2-subtitle: THE CORVUS CLAN
stream-2-url: https://www.youtube.com/playlist?list=PL-rA_OpBnpSoVXVrXAogoGVKgGYpmYV_y?&ab_channel=THECORVUSCLAN
stream-2-image: "/uploads/CorvusClan.jpg"
stream-3-title: How do you react when Jason shows up?
stream-3-subtitle: REACT
stream-3-url: https://www.youtube.com/watch?v=HaeRWY4YKlQ&ab_channel=REACT
stream-3-image: "/uploads/REACT.jpg"
stream-4-title: Typical gameplay, or something more?
stream-4-subtitle: Typical Gamer
stream-4-url: https://www.youtube.com/playlist?list=PLF12pDRgJ2PYUOKbaL5aCSvei3a2f43rE?&ab_channel=TypicalGamer
stream-4-image: "/uploads/Typical%20Gamer.jpg"
stream-5-title: SCREAMING. ALL THE TIME. EVERY TIME!
stream-5-subtitle: CoryxKenshin
stream-5-url: https://www.youtube.com/watch?v=th4oQVNuZVo&ab_channel=CoryxKenshin
stream-5-image: "/uploads/CoryxKenshin.jpg"
stream-6-title: Two enter. None Leave.
stream-6-subtitle: Coisa de Nerd
stream-6-url: https://www.youtube.com/watch?v=6nOE0a1p9ig&ab_channel=CoisadeNerd
stream-6-image: "/uploads/Coisa%20de%20Nerd.jpg"
player-highlight-title: HANGINTHERE
player-highlight-url: http://steamcommunity.com/id/Hanginthere_Aka_Homeslice/
player-highlight-icon-image: "/uploads/player-icon.png"
player-highlight-image: "/uploads/POTW1.jpg"
