---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  content-packs:
    title: Content Packs
    output: true
  in-progress:
    title: In Progress
    output: true
  posts:
    title: Posts
    output: true
  released-patches:
    title: Released Patches
    output: true
  reported-issues:
    title: Reported Issues
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: released-patches
  values:
    released: 'true'
    layout: patchnotes
    release-date: ''
- scope:
    path: ''
    type: content-packs
  values:
    layout: contentpacks
    subtitle: ''
    release-date: ''
    main-image: ''
    one-image: ''
    two-images: ''
    three-images: ''
    featured-image: ''
    released: 'false'
permalink: pretty
Banner Title: We’re Going<br />to PAX
Banner Subtitle: Here's a little something about what’s happening.
Banner Image: "/uploads/banner.jpg"
Upcoming Row 1 Title: AUGUST
Upcoming Row 2 Title: SEPTEMBER
Upcoming Row 3 Title: OCTOBER
