---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  patch-notes:
    title: Patch Notes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: contentpage
    hero-image: ''
- scope:
    path: ''
    type: patch-notes
  values:
    layout: patchnotes
    release-date: ''
- scope:
    path: ''
    type: news
  values:
    layout: contentpage
    subtitle: ''
    main-image: ''
    hero-image: ''
permalink: pretty
banner-image: "/uploads/VC2.0_header.png"
banner-title-line-1: Virtual Cabin 2.0
banner-title-line-2: Nothing is as it Seems
banner-subtitle: New Update includes VC 2.0 free for all platforms!
banner-link-title: Read More
banner-link-url: news/virtual-cabin-2-dot-0-f4eb91
featured-box-1-title: Virtual Cabin 2.0
featured-box-1-subtitle: What it is and why you should care.
featured-box-1-url: news/virtual-cabin-2-dot-0/
new-window-1: false
featured-box-1-image: "/uploads/content_creator-3-30.png"
featured-box-2-title: Content Creator of the Week
featured-box-2-subtitle: IAnthonyD
featured-box-2-url: https://www.youtube.com/Yadigpictures
new-window-2: false
featured-box-2-image: "/uploads/content_creator-3-30-3191ee.png"
featured-box-3-title: Shelly
featured-box-3-subtitle: Welcome back, Shelly!
featured-box-3-url: news/welcome-back-shelly
new-window-3: false
featured-box-3-image: "/uploads/Shelly_featured.png"
stream-1-title: Continual Play
stream-1-subtitle: Esconitz
stream-1-url: https://www.youtube.com/playlist?list=PLvyIAfGy1K6j5CSsvuzUGE_kvmZ-dRtw2
stream-1-image: "/uploads/Esconitz.jpg"
stream-2-title: He's a Ghost
stream-2-subtitle: GhostWolfGames
stream-2-url: https://www.youtube.com/watch?v=KsywZ4kAo-E&list=PLJE0zmCV2Xh2vGsoFJnevsJAcAwRS0X6B
stream-2-image: "/uploads/GhostWolfGames.jpg"
stream-3-title: He Has Game
stream-3-subtitle: TpindellGotGame
stream-3-url: https://www.youtube.com/playlist?list=PLqoaYtms66A1eD3JHjsJOpEm5O4uCuWGo
stream-3-image: "/uploads/TpindellGotGame.jpg"
stream-4-title: 'How agile? '
stream-4-subtitle: I'm Agility
stream-4-url: https://www.youtube.com/channel/UCq2mwSq63nhS5JVoAludkTQ/featured
stream-4-image: "/uploads/ImAgility.jpg"
stream-5-title: Real Life is Hard
stream-5-subtitle: UnseeableNinja
stream-5-url: https://www.youtube.com/watch?v=zz42IEYbfMQ
stream-5-image: "/uploads/Unseeableninja.jpg"
stream-6-title: First to Legitimately Kill Jason
stream-6-subtitle: Fairlight Excalibur
stream-6-url: https://www.youtube.com/watch?v=rHdZVEXvxns
stream-6-image: "/uploads/Fairlight%20Excalibur.jpg"
player-highlight-title: carryondavid
player-highlight-url: 
player-highlight-icon-image: "/uploads/Player%20Highlight%20Icon.png"
player-highlight-image: "/uploads/player_highlight-3_30.png"
