---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  patch-notes:
    title: Patch Notes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: contentpage
    hero-image: ''
- scope:
    path: ''
    type: patch-notes
  values:
    layout: patchnotes
    release-date: ''
- scope:
    path: ''
    type: news
  values:
    layout: contentpage
    subtitle: ''
    main-image: ''
    hero-image: ''
permalink: pretty
banner-image: "/uploads/FRI-01-Jason-RainV2.jpg"
banner-title-line-1: A New
banner-title-line-2: 'Beginning. '
banner-subtitle: We revamped the website for our incredible community of fans!
banner-link-title: Read More
banner-link-url: "/read-more"
featured-box-1-title: Free Emote DLC
featured-box-1-subtitle: Wave at Jason...Just before he kills you.
featured-box-1-url: "/news/emote-dlc-1-2/ "
new-window-1: false
featured-box-1-image: "/uploads/new_emotes-featured.jpg"
featured-box-2-title: Content Creator of the Week
featured-box-2-subtitle: Slash 'N Cast
featured-box-2-url: https://www.youtube.com/user/rjlproductionsprops
new-window-2: true
featured-box-2-image: "/uploads/SlashnCast.png"
featured-box-3-title: Spring Break '84 Clothing Pack
featured-box-3-subtitle: Bikini's, trunks and gore!
featured-box-3-url: "/news/spring-break-1984-clothing-pack/"
new-window-3: false
featured-box-3-image: "/uploads/Spring-Break-Clothing_featured-1.png"
stream-1-title: The nicest person ever to slash you to death!
stream-1-subtitle: ONE_shot_GURL
stream-1-url: https://www.youtube.com/watch?v=WCYb_7wV_UI&list=PLijj2USOOcf9t-Mon-sX2a-akqsa2ck40
stream-1-image: "/uploads/One_Shot_Gurl.jpg"
stream-2-title: Friendship through murder!
stream-2-subtitle: SattelizerGames
stream-2-url: https://www.youtube.com/watch?v=1N7oGMfxQCg&list=PLlkUhqmrrsW1DOWevRZ2l9vI1MHPeDffG
stream-2-image: "/uploads/SattelizerGames.jpg"
stream-3-title: Sohinki So Dead
stream-3-subtitle: Sohinki
stream-3-url: https://www.youtube.com/watch?v=gTAqjic70xs
stream-3-image: "/uploads/Sohinki.jpg"
stream-4-title: Shenanigans
stream-4-subtitle: EdEMonster
stream-4-url: https://www.youtube.com/user/EdEMonster17/search?query=friday+the+13th
stream-4-image: "/uploads/EdEMonster.jpg"
stream-5-title: A list of things you should do when playing F13
stream-5-subtitle: outsidexbox
stream-5-url: https://www.youtube.com/user/outsidexbox/search?query=friday+the+13th
stream-5-image: "/uploads/OutsideXbox.jpg"
stream-6-title: Duking it against Jason
stream-6-subtitle: NukemDukem
stream-6-url: https://www.youtube.com/user/NukemDukem/search?query=friday+the+13th
stream-6-image: "/uploads/NukemDukem.jpg"
player-highlight-title: MissSheDevil69
player-highlight-url: http://steamcommunity.com/id/Hanginthere_Aka_Homeslice/
player-highlight-icon-image: "/uploads/player-icon.png"
player-highlight-image: "/uploads/MissSheDevil.png"
