---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  patch-notes:
    title: Patch Notes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: contentpage
    hero-image: ''
- scope:
    path: ''
    type: patch-notes
  values:
    layout: patchnotes
    release-date: ''
- scope:
    path: ''
    type: news
  values:
    layout: contentpage
    subtitle: ''
    main-image: ''
    hero-image: ''
permalink: pretty
banner-image: "/uploads/Victoria_header-7745e5.png"
banner-title-line-1: Victoria
banner-title-line-2: 
banner-subtitle: 
banner-link-title: Read about our new counselor
banner-link-url: http://f13game.com/news/Victoria/
featured-box-1-title: Virtual Cabin 2.0
featured-box-1-subtitle: What it is and why you should care.
featured-box-1-url: news/virtual-cabin-2-dot-0/
new-window-1: false
featured-box-1-image: "/uploads/content_creator-3-30.png"
featured-box-2-title: Content Creator of the Week
featured-box-2-subtitle: Slash 'N Cast
featured-box-2-url: https://www.youtube.com/user/rjlproductionsprops
new-window-2: false
featured-box-2-image: "/uploads/content-creator_4-26-1977f7.png"
featured-box-3-title: Update Status
featured-box-3-subtitle: 'First Look: Engine Update'
featured-box-3-url: news/update-status/
new-window-3: false
featured-box-3-image: "/uploads/First_look_engine_update_featured.png"
stream-1-title: Salt Mines and Jason 7 Changes
stream-1-subtitle: SleevedBiker
stream-1-url: https://www.youtube.com/watch?v=ztB3h1nDynY
stream-1-image: "/uploads/Stream_1.jpg"
stream-2-title: NEW Jason CHANGES
stream-2-subtitle: IAnthonyD
stream-2-url: https://www.youtube.com/watch?v=tVbs9QyMuBg
stream-2-image: "/uploads/Stream_2.jpg"
stream-3-title: 'F13: The Game Weapon Swap/New Grab DISCUSSION! '
stream-3-subtitle: Slash 'N Cast
stream-3-url: https://www.youtube.com/watch?v=RQB1FRrB3KY
stream-3-image: "/uploads/Stream_3.jpg"
stream-4-title: Friday the 13th Game PARODY 2
stream-4-subtitle: Samination
stream-4-url: https://www.youtube.com/watch?v=y8uBTUcfTeI
stream-4-image: "/uploads/stream_4.jpg"
stream-5-title: 'NEW Part 5 Skin! | Double XP Weekend! | Friday the 13th: The Game'
stream-5-subtitle: Slash 'N Cast
stream-5-url: https://www.youtube.com/watch?v=G9o6hD-OfzM
stream-5-image: "/uploads/Stream_6.jpg"
stream-6-title: 'NEW JASON DLC! '
stream-6-subtitle: Typical Gamer
stream-6-url: https://www.youtube.com/watch?v=hA1hbEGA78E
stream-6-image: "/uploads/stream_5-compressor.jpg"
player-highlight-title: carryondavid
player-highlight-url: 
player-highlight-icon-image: "/uploads/Player%20Highlight%20Icon.png"
player-highlight-image: "/uploads/player_highlight-3_30.png"
