---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  patch-notes:
    title: Patch Notes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: contentpage
    hero-image: ''
- scope:
    path: ''
    type: patch-notes
  values:
    layout: patchnotes
    release-date: ''
- scope:
    path: ''
    type: news
  values:
    layout: contentpage
    subtitle: ''
    main-image: ''
    hero-image: ''
permalink: pretty
banner-image: "/uploads/J4Header.png"
banner-title-line-1: The Final
banner-title-line-2: Chapter.
banner-subtitle: Update to include Jason Part IV and Jarvis Family Home!
banner-link-title: Read More
banner-link-url: 
featured-box-1-title: Virtual Cabin 2.0
featured-box-1-subtitle: What it is and why you should care.
featured-box-1-url: news/virtual-cabin-2-dot-0/
new-window-1: false
featured-box-1-image: "/uploads/content-creator1.png"
featured-box-2-title: Content Creator of the Week
featured-box-2-subtitle: Godenot
featured-box-2-url: https://www.youtube.com/user/SirGodenot
new-window-2: false
featured-box-2-image: "/uploads/content-creator-253352.png"
featured-box-3-title: 'Mitch Floyd '
featured-box-3-subtitle: Comes to Camp Crystal Lake
featured-box-3-url: news/mitchfloyd
new-window-3: false
featured-box-3-image: "/uploads/mitch_hero.png"
stream-1-title: What caliber can take down Jason?
stream-1-subtitle: CALIBER
stream-1-url: https://www.youtube.com/watch?v=1BLWatwB4kU&list=PLmi5t3wYKtQkYLZPbu6RuXL9c0zKJbhEU
stream-1-image: "/uploads/CALIBER.jpg"
stream-2-title: The Deluxe Chad
stream-2-subtitle: TheDeluxe4
stream-2-url: https://www.youtube.com/watch?v=w90EhN5K8BA&list=PLtOkcm5XMWxJ_q1MgmhWU9IvoFYsLuIMP
stream-2-image: "/uploads/TheDeluxe4.jpg"
stream-3-title: Jason Plays Himself
stream-3-subtitle: Play With Jason
stream-3-url: https://www.youtube.com/channel/UCEDjcVfpFC3xxZlZWJ7ZIQQ/featured
stream-3-image: "/uploads/Play%20With%20Jason.jpg"
stream-4-title: 107 Facts about the game
stream-4-subtitle: TheLeaderboard
stream-4-url: https://www.youtube.com/watch?v=Z5ddMtjcVlA
stream-4-image: "/uploads/TheLeaderboard.jpg"
stream-5-title: Big Time Jason
stream-5-subtitle: OpTicBigTymer
stream-5-url: https://www.youtube.com/watch?v=qJaoaNaVCNE&list=PLUMvTIjymG1huQWxRvy0CxJD1TwD5ynju
stream-5-image: "/uploads/OpTicBigTymer.jpg"
stream-6-title: Jason's specialty kills
stream-6-subtitle: Dead Meat
stream-6-url: https://www.youtube.com/channel/UC2IYWWifoIht9T47z1Z5lJw/search?query=friday+the+13th
stream-6-image: "/uploads/Dead%20Meat.jpg"
player-highlight-title: ProdigalBrock
player-highlight-url: https://go.twitch.tv/prodigalbrock
player-highlight-icon-image: "/uploads/player-icon.png"
player-highlight-image: "/uploads/player-highlight-add082.png"
