title: Test
timezone: America/New_York
category_dir: /
baseurl: 
markdown: rdiscount
permalink: pretty
collections:
  content-packs:
    title: Content Packs
    output: true
  in-progress:
    title: In Progress
    output: true
  released-patches:
    title: Released Patches
    output: true
  reported-issues:
    title: Reported Issues
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      type: released-patches
    values:
      released: "true"
      layout: "patchnotes"
      release-date: ""
  - scope:
      type: content-packs
    values:
      layout: "contentpacks"
      subtitle: ""
      release-date: ""
      one-image: ""
      two-images: ""
      three-images: ""
      featured-image: ""
      released: "false"