---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  patch-notes:
    title: Patch Notes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: contentpage
    hero-image: ''
- scope:
    path: ''
    type: patch-notes
  values:
    layout: patchnotes
    release-date: ''
- scope:
    path: ''
    type: news
  values:
    layout: contentpage
    subtitle: ''
    main-image: ''
    hero-image: ''
permalink: pretty
banner-image: "/uploads/FRI-01-Jason-RainV2.jpg"
banner-title-line-1: Dying
banner-title-line-2: For News?
banner-subtitle: Scroll to see what we're working on, patch notes, future content
  and more.
banner-link-title: Read More
banner-link-url: "/read-more"
featured-box-1-title: Featured Content
featured-box-1-subtitle: Emote DLC Pack 1
featured-box-1-url: "/news/emote-dlc-1-2/ "
featured-box-1-image: "/uploads/new_emotes-featured.jpg"
featured-box-2-title: Streamer of the Week
featured-box-2-subtitle: Swag_Dracula
featured-box-2-url: http://www.google.com
featured-box-2-image: "/uploads/featured2.jpg"
featured-box-3-title: Spring Break '84 Clothing Pack
featured-box-3-subtitle: Righteous threads
featured-box-3-url: http://www.google.com
featured-box-3-image: "/uploads/springbreak-featured.jpg"
stream-1-title: 'Bikini Stream <3 #NOTCLICKBAIT More text more'
stream-1-subtitle: SattelizerGames
stream-1-url: http://www.twitch.com
stream-1-image: "/uploads/stream1.jpg"
stream-2-title: 40% Smaller Maps = $40 Game More Text More
stream-2-subtitle: Avajaijai
stream-2-url: http://www.twitch.com
stream-2-image: "/uploads/stream2.jpg"
stream-3-title: 40% Smaller Maps = $40 Game More Text More
stream-3-subtitle: Avajaijai
stream-3-url: http://www.twitch.com
stream-3-image: "/uploads/stream2.jpg"
stream-4-title: 'Bikini Stream <3 #NOTCLICKBAIT More text more'
stream-4-subtitle: SattelizerGames
stream-4-url: http://www.twitch.com
stream-4-image: "/uploads/stream1.jpg"
stream-5-title: 'Bikini Stream <3 #NOTCLICKBAIT More text more'
stream-5-subtitle: SattelizerGames
stream-5-url: http://www.twitch.com
stream-5-image: "/uploads/stream1.jpg"
stream-6-title: 40% Smaller Maps = $40 Game More Text More
stream-6-subtitle: Avajaijai
stream-6-url: http://www.twitch.com
stream-6-image: "/uploads/stream2.jpg"
player-highlight-title: DeFaUlT_AnOn
player-highlight-url: http://www.twitch.com
player-highlight-icon-image: "/uploads/player-icon.png"
player-highlight-image: "/uploads/player-highlight.jpg"
