---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  patch-notes:
    title: Patch Notes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: contentpage
    hero-image: ''
- scope:
    path: ''
    type: patch-notes
  values:
    layout: patchnotes
    release-date: ''
- scope:
    path: ''
    type: news
  values:
    layout: contentpage
    subtitle: ''
    main-image: ''
    hero-image: ''
permalink: pretty
banner-image: "/uploads/VC2.0_header.png"
banner-title-line-1: Virtual Cabin 2.0
banner-title-line-2: Nothing is as it Seems
banner-subtitle: New Update includes VC 2.0 free for all platforms!
banner-link-title: Read More
banner-link-url: news/virtual-cabin-2-dot-0
featured-box-1-title: Virtual Cabin 2.0
featured-box-1-subtitle: What it is and why you should care.
featured-box-1-url: news/virtual-cabin-2-dot-0/
new-window-1: false
featured-box-1-image: "/uploads/content-creator1.png"
featured-box-2-title: Content Creator of the Week
featured-box-2-subtitle: Mad-Eye Yokai
featured-box-2-url: https://www.youtube.com/channel/UCS2aOO9sul3irSVS8yM9RxA
new-window-2: false
featured-box-2-image: "/uploads/content-creator.png"
featured-box-3-title: Fox
featured-box-3-subtitle: Returns to Camp Crystal Lake
featured-box-3-url: news/fox
new-window-3: false
featured-box-3-image: "/uploads/fox_featured.png"
stream-1-title: He's Terrified!
stream-1-subtitle: TmarTn2
stream-1-url: https://www.youtube.com/watch?v=g7ONBo-h-Bs&list=PLwiTZDxPg_I2npk3IwPvq88be4_fmaWqW
stream-1-image: "/uploads/Tmartn2.jpg"
stream-2-title: Who's Behind the Camera?
stream-2-subtitle: KidBehindACamera
stream-2-url: https://www.youtube.com/user/KidBehindACamera/search?query=friday+the+13th
stream-2-image: "/uploads/KidBehindaCamera.jpg"
stream-3-title: A Parody Animation
stream-3-subtitle: Samination
stream-3-url: https://www.youtube.com/watch?v=hiZX35fettA
stream-3-image: "/uploads/Samination.jpg"
stream-4-title: A Parody Live-Video
stream-4-subtitle: Oddest of the Odd
stream-4-url: https://www.youtube.com/watch?v=3ktayCWti2A&t=3s
stream-4-image: "/uploads/Oddest%20of%20the%20Odd.jpg"
stream-5-title: Jason visits Germany!
stream-5-subtitle: tyraphine
stream-5-url: https://www.youtube.com/user/tyraphine/search?query=friday+the+13th
stream-5-image: "/uploads/tyrpahine.jpg"
stream-6-title: Jason also visits Greece
stream-6-subtitle: Vela Games GR
stream-6-url: https://www.youtube.com/watch?v=wQrs36qDfbE&list=PLrnzSSiMRIThk45JXQv62Q6YupXOPSnt1
stream-6-image: "/uploads/Vela%20Games%20GR.jpg"
player-highlight-title: "™Tommy™ | SSGSS"
player-highlight-url: http://steamcommunity.com/id/SSR_TomKu
player-highlight-icon-image: "/uploads/Player%20Highlight%20Icon.png"
player-highlight-image: "/uploads/player-highlight-bff109.png"
