---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  patch-notes:
    title: Patch Notes
    output: true
  posts:
    title: Posts
    output: true
  streams:
    title: Streams
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: contentpage
- scope:
    path: ''
    type: patch-notes
  values:
    layout: patchnotes
    release-date: ''
- scope:
    path: ''
    type: news
  values:
    layout: news
    subtitle: ''
    main-image: ''
    hero-image: ''
permalink: pretty
banner-image: "/uploads/FRI-01-Jason-RainV2.jpg"
banner-title-line-1: Dying
banner-title-line-2: For News?
banner-subtitle: Scroll to see what we're working on, patch notes, future content
  and more.
banner-link-title: Read More
banner-link-url: "/read-more"
featured-box-1-title: 
featured-box-1-subtitle: 
featured-box-1-url: 
featured-box-1-image: 
featued-box-2-title: 
featured-box-2-subtitle: 
featured-box-2-url: 
featured-box-2-image: 
featured-box-3-title: 
featured-box-3-subtitle: 
featured-box-3-url: 
featured-box-3-image: 
player-highlight-title: DeFaUlT_AnOn
player-highlight-icon-image: 
player-highlight-image: 
