---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  patch-notes:
    title: Patch Notes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: contentpage
    hero-image: ''
- scope:
    path: ''
    type: patch-notes
  values:
    layout: patchnotes
    release-date: ''
- scope:
    path: ''
    type: news
  values:
    layout: contentpage
    subtitle: ''
    main-image: ''
    hero-image: ''
permalink: pretty
banner-image: "/uploads/FRI-01-Jason-RainV2.jpg"
banner-title-line-1: A New
banner-title-line-2: 'Beginning. '
banner-subtitle: We revamped the website for our incredible community of fans!
banner-link-title: Read More
banner-link-url: "/read-more"
featured-box-1-title: Free Emote DLC
featured-box-1-subtitle: Wave at Jason...Just before he kills you.
featured-box-1-url: "/news/emote-dlc-1-2/ "
new-window-1: false
featured-box-1-image: "/uploads/new_emotes-featured.jpg"
featured-box-2-title: Content Creator of the Week
featured-box-2-subtitle: Jason Takes Omegle
featured-box-2-url: https://jasontakesomegle.com/
new-window-2: false
featured-box-2-image: "/uploads/omegleheader.png"
featured-box-3-title: Spring Break '84 Clothing Pack
featured-box-3-subtitle: Bikini's, trunks and gore!
featured-box-3-url: "/news/spring-break-1984-clothing-pack/"
new-window-3: false
featured-box-3-image: "/uploads/Spring-Break-Clothing_featured-1.png"
stream-1-title: A full on music video!
stream-1-subtitle: Kronno Zomber + Cyclo
stream-1-url: https://www.youtube.com/watch?v=JxCZsOBWV2M
stream-1-image: "/uploads/Kronno%20Zomber.jpg"
stream-2-title: Rapping from Turkey!
stream-2-subtitle: Uğur Yılmaz
stream-2-url: https://www.youtube.com/watch?v=cr5PLYICRkk
stream-2-image: "/uploads/U%C4%9Fur%20Y%C4%B1lmaz.jpg"
stream-3-title: A collab with Daddyphatsnaps + Bonecage
stream-3-subtitle: Dan Bull
stream-3-url: https://www.youtube.com/watch?v=28_b_NziqkM
stream-3-image: "/uploads/Dan%20Bull.jpg"
stream-4-title: He will splatter your crown
stream-4-subtitle: Daddyphatsnaps
stream-4-url: https://www.youtube.com/watch?v=W8FIfBOpGv8
stream-4-image: "/uploads/Daddyphatsnaps.jpg"
stream-5-title: A whole mess of different raps, all from Crystal Lake
stream-5-subtitle: Rockit Gaming
stream-5-url: https://www.youtube.com/channel/UCT8iW11Pk6HLELCH_mcaQNA/search?query=friday+the+13th
stream-5-image: "/uploads/Rockit%20Gaming.jpg"
stream-6-title: Even in Spain, you can't escape Jason
stream-6-subtitle: BersGamer
stream-6-url: https://www.youtube.com/user/BersGamer/search?query=friday+the+13th
stream-6-image: "/uploads/BersGamer.jpg"
player-highlight-title: aSiAnZz-_-ChArMz
player-highlight-url: 
player-highlight-icon-image: "/uploads/player-icon.png"
player-highlight-image: "/uploads/asian%20charmz.png"
