---
title: Friday the 13th The Game
timezone: America/New_York
collections:
  content-packs:
    title: Content Packs
    output: true
  in-progress:
    title: In Progress
    output: true
  posts:
    title: Posts
    output: true
  released-patches:
    title: Released Patches
    output: true
  reported-issues:
    title: Reported Issues
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    type: released-patches
  values:
    released: "true"
    layout: "patchnotes"
    release-date: ""
- scope:
    type: content-packs
   values:
    layout: "contentpacks"
    subtitle: ""
    release-date: ""
    one-image: ""
    two-images: ""
    three-images: ""
    featured-image: ""
    released: "false"
permalink: pretty
