---
title: Friday the 13th the Game
timezone: America/New_York
collections:
  in-progress:
    title: In Progress
    output: true
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  released-patches:
    title: Released Patches
    output: true
  reported-issues:
    title: Reported Issues
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: contentpage
- scope:
    path: ''
    type: released-patches
  values:
    released: 'true'
    layout: patchnotes
    release-date: ''
- scope:
    path: ''
    type: news
  values:
    layout: news
    subtitle: ''
    main-image: ''
    hero-image: ''
permalink: pretty
banner-image: "/uploads/FRI-01-Jason-RainV2.jpg"
banner-title-line-1: Dying
banner-title-line-2: For News?
banner-subtitle: Scroll to see what we're working on, patch notes, future content
  and more.
banner-link-title: Read More
banner-link-url: "/read-more"
